### ISSUE TITLE
initialize('UA-XXXXX-YY') not working

### ISSUE THREAD

**Issue by raghu64** [daxko/universal-ga#1]
Hi i was new to google analytics and i want to implement GA in my nodejs code.

when the execution step reaches the analytics.initialize('UA-XXXXXX-YY', {debug: true}), its throwing error to client side angular app.

var analytics = require('universal-ga');
analytics.initialize('UA-XXXXXX-YY',{debug: true});

Can you please help to figure out the mistake that i'm doing here?

Thanks.

**Comment by actuallymentor** [comment]
Maybe give us the error as well.

**Comment by scurker** [comment]
Hi @raghu64, I'd love to help but I don't have a lot of context into what you're seeing without some errors. If you can provide a few more details, I can reopen this if it's an issue.
